apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-deploy-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: java-container
        image: deepikaarjunan/spring-boot:v3
        ports:
        - containerPort: 8080
