apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-container
        image: deepikaarjunan/spring-boot:v2
        ports:
        - containerPort: 8289
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
  labels:
    app: springboot-app
spec:
  selector:
    app: java-deployment-label

  type: NodePort
  ports:
    port: 80
    targetPort: 8289
