apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deploy
  labels:
    app: devops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-container
        image: deepikaarjunan/java-project:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops-app
spec:
  selector:
    app: devops-deploy-lbl

  type: NodePort
  ports:
    port: 80
    targetPort: 8080
