apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
  labels:
    app: springboot-deploy-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-project
  template:
    metadata:
      labels:
        app: my-project
    spec:
      containers:
      - name: springboot-container
        image: deepikaarjunan/spring-boot:image1
        ports:
        - containerPort: 8289

---
apiVersion: v1
kind: Services
metadata:
  label: port-svc
spec:
  selector:
    matchLabels:
      app: springboot-deploy-java
      
  type: NodePort
  ports:
  - NodePort: 32100
    port: 8289
    targetPort: 8289
